In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import cv2
import imutils
from PIL import ImageColor
from scipy.spatial.distance import euclidean
# from scipy.spatial.distance import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances
# from collections import OrderedDict 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [51]:
##Lego colours
##https://brickipedia.fandom.com/wiki/Colour_Palette

legoColoursHEX = {"brightRed" : '#DE000D',
                  "brightBlue" : '#0057A8',
                  "darkGreen" : '#007B28',
                 "mediumBlue" : "#478CC6"}
legoColoursRGB = dict((k, ImageColor.getcolor(v, "RGB"))for k,v in legoColoursHEX.items())
legoColoursBGR = dict((k, ImageColor.getcolor(v, "RGB")[::-1])for k,v in legoColoursHEX.items())

df = pd.DataFrame([[k,v] for k,v in legoColoursBGR.items()], columns = ['colour','BGR'])

In [52]:
df

colour             BGR
0   brightRed    (13, 0, 222)
1  brightBlue    (168, 87, 0)
2   darkGreen    (40, 123, 0)
3  mediumBlue  (198, 140, 71)

In [ ]:
legoColourNames = ['brightRed', 'brightBlue']

In [15]:
legoColoursRGB

{'brightRed': (222, 0, 13),
 'brightBlue': (0, 87, 168),
 'darkGreen': (0, 123, 40),
 'mediumBlue': (71, 140, 198)}

In [16]:
legoColoursBGR

{'brightRed': (13, 0, 222),
 'brightBlue': (168, 87, 0),
 'darkGreen': (40, 123, 0),
 'mediumBlue': (198, 140, 71)}

In [32]:
bgrArray = np.array([np.array(v) for v in legoColoursBGR.values()])

In [33]:
bgrArray

array([[ 13,   0, 222],
       [168,  87,   0],
       [ 40, 123,   0],
       [198, 140,  71]])

In [34]:
bgrArray.shape

(4, 3)

In [19]:
inputVector = np.array([13, 0, 222])
inputVector

array([ 13,   0, 222])

In [39]:
euclidean(inputVector, inputVector)

0.0

In [54]:
dist

array([[  0.        ],
       [284.3905765 ],
       [255.22930866],
       [276.81401699]])

In [58]:
dist = euclidean_distances(bgrArray, np.array([inputVector]))
idx = dist.argmin()
df.iloc[0]['colour']

'brightRed'

# Using K-Nearest Neighbors

In [12]:
df2 = pd.read_csv('./Colour Data/colourdata.csv')
df2[['r','g','b']]
# df2.shape

r    g    b
0  185  146   55
1  189  151   69
2  141  179  209
3   18   90  146
4   73  121  169
5  168  106  106
6  144   29   10
7  147   30   13

In [47]:
KNN = KNeighborsClassifier()
scaler = StandardScaler()
# X = scaler.fit_transform(df2[['r','g','b']])
X = df2[['r','g','b']]
y = df2[['Label']].values.ravel()
KNN.fit(X,y)

KNeighborsClassifier()

In [56]:
bgr = (0, 87, 168)
bgr2 = (185,146,55)
target = np.array([bgr2])
KNN.predict(target)[0]

'brightRed'

In [35]:
X

array([[ 0.94180369,  0.76844032, -0.61623812],
       [ 1.01442469,  0.86571124, -0.41143494],
       [ 0.14297261,  1.41042843,  1.63659678],
       [-2.09012336, -0.32099406,  0.7149825 ],
       [-1.09158451,  0.28208569,  1.05144486],
       [ 0.63316441, -0.00972709,  0.12983058],
       [ 0.19743836, -1.50769936, -1.27453403],
       [ 0.25190412, -1.48824517, -1.23064764]])

In [42]:
df2[['r','g','b']].to_numpy()

array([[185, 146,  55],
       [189, 151,  69],
       [141, 179, 209],
       [ 18,  90, 146],
       [ 73, 121, 169],
       [168, 106, 106],
       [144,  29,  10],
       [147,  30,  13]], dtype=int64)

In [43]:
np.array([bgr2])

array([[185, 146,  55]])

In [61]:
target = np.array([bgr2[::-1]])
target

array([[ 55, 146, 185]])